name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Pest PHP Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD || 'github_actions' }}
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql
        coverage: xdebug

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Update .env for testing
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=testing" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD || 'github_actions' }}" >> .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Configure Database
      run: |
        php artisan config:clear
        php artisan migrate --force

    - name: Create test directories if they don't exist
      run: |
        mkdir -p tests/Unit
        mkdir -p tests/Feature
        touch tests/Unit/.gitkeep
        touch tests/Feature/.gitkeep

    - name: Install Pest if not already installed
      run: |
        if ! [ -f vendor/bin/pest ]; then
          composer require pestphp/pest --dev
          php artisan pest:install
        fi

    - name: Execute tests
      run: |
        if [ -f vendor/bin/pest ]; then
          vendor/bin/pest
        else
          echo "Pest not found, falling back to PHPUnit"
          vendor/bin/phpunit
        fi